### ISSUE TITLE
是不是不能再WSL2环境下运行呀

### ISSUE THREAD

**Issue by liangyijian1** [IgnorAnsel/QBlueprint#12]
运行可执行文件的时候报错了：

Failed to create wl_display (No such file or directory)
qt.qpa.plugin: Could not load the Qt platform plugin "wayland" in "" even though it was found.
: 1
*** stack smashing detected ***: terminated
Aborted

**Comment by IgnorAnsel** [comment]
> 运行可执行文件的时候报错了：
> 
> 创建wl_display失败（无此类文件或目录）qt.qpa.plugin：即使找到Qt平台插件“wayland”，也无法在“”中加载它。 ： 1 *** 检测到堆栈粉碎 ***： 终止 中止

export QT_QPA_PLATFORM=xcb

试试加上这个

**Comment by liangyijian1** [comment]
> > 运行可执行文件的时候报错了：
> > 创建wl_display失败（无此类文件或目录）qt.qpa.plugin：即使找到Qt平台插件“wayland”，也无法在“”中加载它。 ： 1 *** 检测到堆栈粉碎 ***： 终止 中止
> 
> export QT_QPA_PLATFORM=xcb
> 
> 试试加上这个

lh@DESKTOP-T69NSGE:/prj/QBlueprint/build$ export QT_QPA_PLATFORM=xcb
lh@DESKTOP-T69NSGE:/prj/QBlueprint/build$ ./QBlueprint
: 1
Illegal instruction

还是有错误

**Comment by IgnorAnsel** [comment]
> > > 运行可执行文件的时候报错了：
> > > 创建wl_display失败（无此类文件或目录）qt.qpa.plugin：即使找到Qt平台插件“wayland”，也无法在“”中加载它。 ： 1 *** 检测到堆栈粉碎 ***： 终止 中止
> > 
> > 
> > export QT_QPA_PLATFORM=xcb
> > 试试加上这个
> 
> lh@DESKTOP-T69NSGE:/prj/QBlueprint/build$ export QT_QPA_PLATFORM=xcb lh@DESKTOP-T69NSGE:/prj/QBlueprint/build$ ./QBlueprint : 1 Illegal instruction
> 
> 还是有错误

你的桌面是wayland吗

**Comment by IgnorAnsel** [comment]
> > > 运行可执行文件的时候报错了：
> > > 创建wl_display失败（无此类文件或目录）qt.qpa.plugin：即使找到Qt平台插件“wayland”，也无法在“”中加载它。 ： 1 *** 检测到堆栈粉碎 ***： 终止 中止
> > 
> > 
> > export QT_QPA_PLATFORM=xcb
> > 试试加上这个
> 
> lh@DESKTOP-T69NSGE:/prj/QBlueprint/build$ export QT_QPA_PLATFORM=xcb lh@DESKTOP-T69NSGE:/prj/QBlueprint/build$ ./QBlueprint : 1 Illegal instruction
> 
> 还是有错误

export QT_QPA_PLATFORM=xcb需要加在cmakelist内

**Comment by liangyijian1** [comment]
> > > > 运行可执行文件的时候报错了：
> > > > 创建wl_display失败（无此类文件或目录）qt.qpa.plugin：即使找到Qt平台插件“wayland”，也无法在“”中加载它。 ： 1 *** 检测到堆栈粉碎 ***： 终止 中止
> > > 
> > > 
> > > export QT_QPA_PLATFORM=xcb
> > > 试试加上这个
> > 
> > 
> > lh@DESKTOP-T69NSGE:/prj/QBlueprint/build$ export QT_QPA_PLATFORM=xcb lh@DESKTOP-T69NSGE:/prj/QBlueprint/build$ ./QBlueprint : 1 Illegal instruction
> > 还是有错误
> 
> export QT_QPA_PLATFORM=xcb需要加在cmakelist内

我尝试了在CMakeLists.txt中加入了
set_target_properties(QBlueprint PROPERTIES
  ENVIRONMENT "QT_QPA_PLATFORM=xcb"
)
但是还是无法运行，显示
lh@DESKTOP-T69NSGE:~/prj/QBlueprint/build1$ ./QBlueprint
: 1
Illegal instruction
我的cmake ..运行结果是

lh@DESKTOP-T69NSGE:/prj/QBlueprint/build1$ cmake ..
-- The CXX compiler identification is GNU 13.2.0
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE
-- Performing Test HAVE_STDATOMIC
-- Performing Test HAVE_STDATOMIC - Success
-- Found WrapAtomic: TRUE
-- Found OpenGL: /usr/lib/x86_64-linux-gnu/libOpenGL.so
-- Found WrapOpenGL: TRUE
-- Found XKB: /usr/lib/x86_64-linux-gnu/libxkbcommon.so (found suitable version "1.6.0", minimum required is "0.5.0")
-- Found WrapVulkanHeaders: /usr/include
-- Configuring done (2.8s)
-- Generating done (0.0s)
-- Build files have been written to: /home/lh/prj/QBlueprint/build1

**Comment by liangyijian1** [comment]
> > > > 运行可执行文件的时候报错了：
> > > > 创建wl_display失败（无此类文件或目录）qt.qpa.plugin：即使找到Qt平台插件“wayland”，也无法在“”中加载它。 ： 1 *** 检测到堆栈粉碎 ***： 终止 中止
> > > 
> > > 
> > > export QT_QPA_PLATFORM=xcb
> > > 试试加上这个
> > 
> > 
> > lh@DESKTOP-T69NSGE:/prj/QBlueprint/build$ export QT_QPA_PLATFORM=xcb lh@DESKTOP-T69NSGE:/prj/QBlueprint/build$ ./QBlueprint : 1 Illegal instruction
> > 还是有错误
> 
> 你的桌面是wayland吗

环境应该是xcb，我安装了libxcb有关的库
sudo apt install libxcb-*

**Comment by IgnorAnsel** [comment]
这就很难评了，没有wsl2的设备，无法直接上手调试，不过这种问题网上大概率会有（多半配置问题应该代码问题不大），如果实在无法解决我会搞下wsl2的。:()


---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年09月30日 15:48 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [IgnorAnsel/QBlueprint] 是不是不能再WSL2环境下运行呀 (Issue #12) |

运行可执行文件的时候报错了：
创建wl_display失败（无此类文件或目录）qt.qpa.plugin：即使找到Qt平台插件“wayland”，也无法在“”中加载它。 ： 1 *** 检测到堆栈粉碎 ***： 终止 中止

export QT_QPA_PLATFORM=xcb
试试加上这个

***@***.***:/prj/QBlueprint/build$ export QT_QPA_PLATFORM=xcb ***@***.***:/prj/QBlueprint/build$ ./QBlueprint : 1 Illegal instruction
还是有错误

你的桌面是wayland吗

环境应该是xcb，我安装了libxcb有关的库
