### ISSUE TITLE
this project don't direct running in the windows

### ISSUE THREAD

**Issue by warmtan** [IgnorAnsel/QBlueprint#2]

**Comment by IgnorAnsel** [comment]
You can provide me with the compilation errors, and I will fix them.

**Comment by IgnorAnsel** [comment]
> _未提供描述。_


You can provide me with the compilation errors, and I will fix them.

**Comment by warmtan** [comment]
D:\Cpp_project\QBlueprint-4.2.0\testclass.cpp:16: error: C4716: 'TestClass::test': must return a value 
D:\Cpp_project\QBlueprint-4.2.0\qnodefactory.h:35: error: C2027: use of undefined type 'QBlueprint'
D:\Cpp_project\QBlueprint-4.2.0\qnodefactory.h(35): error C2027: use of undefined type 'QBlueprint'
D:\Cpp_project\QBlueprint-4.2.0\qblueprintport.h(8): note: see declaration of 'QBlueprint'
D:\Cpp_project\QBlueprint-4.2.0\qnodefactory.h(16): note: This diagnostic occurred in the compiler generated function 'QBlueprintNode *QNodeFactory::createNodeFromFunction(QBlueprint *,Func,const QString &,const QString &)'

**Comment by IgnorAnsel** [comment]
> D：\Cpp_project\QBlueprint-4.2.0\testclass.cpp：16：错误：C4716：“TestClass：：test”：必须返回一个值 D：\Cpp_project\QBlueprint-4.2.0\qnodefactory.h：35：错误：C2027：使用未定义的类型 'QBlueprint' D：\Cpp_project\QBlueprint-4.2.0\qnodefactory.h（35）：错误 C2027：使用未定义的类型 'QBlueprint' D：\Cpp_project\QBlueprint-4.2.0\qblueprintport.h（8）：注意：参见 'QBlueprint' 的声明D：\Cpp_project\QBlueprint-4.2.0\qnodefactory.h（16）：注意：此诊断发生在编译器生成的函数“QBlueprintNode *QNodeFactory：：createNodeFromFunction（QBlueprint *，Func，const QString &，const QString &）”中

Can you pull the latest master branch to check if the bug has been fixed?

**Comment by IgnorAnsel** [comment]
> D：\Cpp_project\QBlueprint-4.2.0\testclass.cpp：16：错误：C4716：“TestClass：：test”：必须返回一个值 D：\Cpp_project\QBlueprint-4.2.0\qnodefactory.h：35：错误：C2027：使用未定义的类型 'QBlueprint' D：\Cpp_project\QBlueprint-4.2.0\qnodefactory.h（35）：错误 C2027：使用未定义的类型 'QBlueprint' D：\Cpp_project\QBlueprint-4.2.0\qblueprintport.h（8）：注意：参见 'QBlueprint'的声明D：\Cpp_project\QBlueprint-4.2.0\qnodefactory.h（16）：注意：此诊断发生在编译器生成的函数“QBlueprintNode *QNodeFactory：：createNodeFromFunction（QBlueprint *，Func，const QString &，const QString &）”中

Looking forward to your response.
